# Generated by Django 5.1.5 on 2025-01-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(choices=[('za', 'Za'), ('przeciw', 'Przeciw'), ('wstrzymal sie', 'Wstrzymał się')], max_length=20),
        ),
    ]
