import type { Metadata } from "next";

import "/src/app/globals.css";

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-zinc-300 h-12 flex items-center p-3 w-full justify-between">
          <div className="text-xl">Panel admina</div>
        </div>
        {children}
      </body>
    </html>
  );
}
